<x-app-layout>
    <div class="max-w-4xl mx-auto px-6 py-12">
        <!-- Title -->
        <h1 class="text-3xl font-bold text-gray-900 dark:text-gray-100 mb-4">
            {{ $advice->title }}
        </h1>

        <!-- Meta info -->
        <div class="text-sm text-gray-500 dark:text-gray-400 mb-6">
            <span>Generated by: 
                <span class="font-semibold text-gray-700 dark:text-gray-200">
                    {{ ucfirst($advice->generated_by) }}
                </span>
            </span> • 
            <span>{{ $advice->created_at->format('M d, Y H:i') }}</span>
        </div>

        <!-- Content -->
        <div class="bg-white dark:bg-gray-800 rounded-xl shadow p-6 border border-gray-200 dark:border-gray-700">
            <p class="text-lg text-gray-700 dark:text-gray-200 leading-relaxed">
                {{ $advice->content }}
            </p>
        </div>

        <!-- Actions -->
        <div class="mt-6 flex space-x-4">
            <!-- Start Chat -->
            <a href="{{ route('chat.sessions.start', $advice->id) }}"
               class="bg-green-600 hover:bg-green-700 text-white px-6 py-3 rounded-lg font-semibold transition">
                Start Chat
            </a>

            <!-- Back to advices -->
            <a href="{{ route('advices.index') }}"
               class="bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-gray-800 dark:text-gray-200 px-6 py-3 rounded-lg font-semibold transition">
                Back to Advice List
            </a>
        </div>
    </div>
</x-app-layout>
